# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


# IDE录制的脚本
class TestSearch():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_search(self):
        self.driver.get("https://testerhome.com/")
        self.driver.set_window_size(1440, 900)
        self.driver.find_element(By.NAME, "q").click()
        self.driver.find_element(By.NAME, "q").send_keys("appium")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)


class TestTesterHome:

    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)
        self.driver.get('https://testerhome.com/')


    def teardown_method(self):
        time.sleep(5)
        self.driver.quit()


    def test_mainpage(self):
        self.driver.find_element(By.CSS_SELECTOR, '#main-nav-menu > ul > li:nth-child(4) > a').click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR,
                             'div.panel-body > div > div:nth-child(1) > div > div.media-body > div.media-heading > a').click()
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR,
                             'div.panel-body > div:nth-child(1) > div.infos.media-body > div.title.media-heading > a').click()
